### ISSUE TITLE
Image always displays

### ISSUE THREAD

**Issue by shagtimetim** [oemel09/MMM-DailyPower#1]
We have set the config as follows; however, the image displays.
module: "MMM-DailyPower",
        position: "top_left",       // This can be any region
        config: {		     // See 'Configuration options' for more information.
		translation: "akjv",
		width: "33%",
		showImage: "false",
		margin: "0",
		blackAndWhite: "false"

**Comment by oemel09** [comment]
`showImage` and `blackAndWhite` are boolean values. Use `true` or `false` without any quotation marks and it should work fine.
Thanks for using my module and reaching out for help! 

Please let me know or close the issue if it helped.

**Comment by shagtimetim** [comment]
Yes, that took care of it!  Thank you!!
